function disc1(){
    alert("Microsoft Azure:  a close up of a device        Moblinet : Moniter   Azure    IS MORE ACCURATE");
}
function disc2(){
    alert("Microsoft Azure:  a close up of a remote control        Moblinet : CD,Laptop   Azure  IS MORE ACCURATE");
}
function disc3(){
    alert("Microsoft Azure:  a small room        Moblinet : Eggis,Breastplate   Azure   IS MORE ACCURATE");
}
function disc4(){
    alert("Microsoft Azure:   undefined       Moblinet :  Laptop Computer   Moblinet  IS MORE ACCURATE");
}
function disc5(){
    alert("Microsoft Azure:   a close up of a game       Moblinet :  punching bag,television Azure   IS MORE ACCURATE");
}
function disc6(){
    alert("Microsoft Azure:   shower curtain       Moblinet :aTelevision  Azure IS MORE ACCURATE");
}
function disc8(){
    alert("Microsoft Azure:   a bedroom with a bed and chair       Moblinet :   Home theater Azure   IS MORE ACCURATE");
}
function disc7(){
    alert("Microsoft Azure:   a cup of coffee       Moblinet :  Spotlight,hamper   Moblinet    IS MORE ACCURATE");
}
function disc9(){
    alert("Microsoft Azure:   undefined       Moblinet :  undefined    Cannot Say     IS MORE ACCURATE");
}
